name: 'thelook_analytics'
version: '1.0.0'
config-version: 2

profile: 'thelook_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  thelook_analytics:
    staging:
      +schema: stg
      +materialized: view

    intermediate:
      +schema: int
      +materialized: view

    marts:
      +schema: mart
      +materialized: table
