version: 2

sources:
  - name: raw
    database: looker-analytics88476
    schema: raw
    tables:
      - name: orders
      - name: orders_items
      - name: users
      - name: products
      - name: events